### ISSUE TITLE
Hola, esto ya no funciona? 

### ISSUE THREAD

**Issue by chuntin** [GeoAPI-es/geoapi.es-php#1]
no se sigue actualizando la librería?

La intento usar con symfony pero no funciona por lo que me tendría que crear una.

Un saludo

**Comment by alexandernst** [comment]
Hola! La lib no tiene actualizaciones porque la API no ha cambiado. Cual es el problema que ves? Puedes copiar tu código (junto con el error) en pastebin?

**Comment by chuntin** [comment]
Hola, en el archivo lo veo correcto pero cuando he instalado la libreria la url estaba mal por ejemplo. aunque veo que en el git si que esta correcta.

**Comment by alexandernst** [comment]
La URL deberia estar bien. Has probado a ejecutar la demo de PHP (https://github.com/GeoAPI-es/geoapi.es-php/blob/master/demo/GeoAPI_example.php) fuera de tu proyecto?

**Comment by chuntin** [comment]
creo que al usar composer me había instalado una version anterior, pero ya he actualizado y ahora bién. Lo que no se es como conseguir una key. he escrito correo a soporte a ver que me dicen.

**Comment by alexandernst** [comment]
Te hemos contestado al correo! ;)
Damos esto por cerrado?

**Comment by chuntin** [comment]
si, claro. Gracias por la ayuda
