### ISSUE TITLE
Problemas con el CUN de algunos municipios

### ISSUE THREAD

**Issue by adrydam** [GeoAPI-es/geoapi.es-php#2]
Hola!

Parece que los municipios de Las Palmas tienen un CUN = 0000000, por lo que no puedo obtener los códigos postales para ellos. No sé si hay alguna otra forma de obtenerlos sin utilizar el CUN pero no me lo ha parecido viendo la docu. 

La URL a la que estoy llamando es la siguiente:
_https://apiv1.geoapi.es/municipios?CPRO=35&type=JSON&key=&sandbox=1_

Gracias!

**Comment by alexandernst** [comment]
Hola! Fijate como has de implementarlo siguiendo la pagina demo: https://geoapi.es/pruebalo

**Comment by adrydam** [comment]
Gracias por la respuesta! 
No había visto la demo, solucionado 💃
